// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3osAlPUFMSQTnzn4-F_2Q67Bb9yR3UgA',
    appId: '1:1027050882571:web:8d72e3ecca365da1dd690e',
    messagingSenderId: '1027050882571',
    projectId: 'do-it-app-c8de3',
    authDomain: 'do-it-app-c8de3.firebaseapp.com',
    storageBucket: 'do-it-app-c8de3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCucJciT0_68YkhmJx3rNAKYwa21wAOSpw',
    appId: '1:1027050882571:android:9d30fe503007dde5dd690e',
    messagingSenderId: '1027050882571',
    projectId: 'do-it-app-c8de3',
    storageBucket: 'do-it-app-c8de3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArqYeqXEFAgvdWWQ1qqzYnJRVTY_I1HzQ',
    appId: '1:1027050882571:ios:f305b3086dfc5315dd690e',
    messagingSenderId: '1027050882571',
    projectId: 'do-it-app-c8de3',
    storageBucket: 'do-it-app-c8de3.firebasestorage.app',
    iosBundleId: 'com.example.doItApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArqYeqXEFAgvdWWQ1qqzYnJRVTY_I1HzQ',
    appId: '1:1027050882571:ios:f305b3086dfc5315dd690e',
    messagingSenderId: '1027050882571',
    projectId: 'do-it-app-c8de3',
    storageBucket: 'do-it-app-c8de3.firebasestorage.app',
    iosBundleId: 'com.example.doItApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3osAlPUFMSQTnzn4-F_2Q67Bb9yR3UgA',
    appId: '1:1027050882571:web:3c4b21a326c2c83fdd690e',
    messagingSenderId: '1027050882571',
    projectId: 'do-it-app-c8de3',
    authDomain: 'do-it-app-c8de3.firebaseapp.com',
    storageBucket: 'do-it-app-c8de3.firebasestorage.app',
  );
}
